### PR TITLE
Update mod to 1.16.3/1.16.4

### PR DESCRIPTION
**Pull request by Lakuna**

### CODE REVIEW

**Comment by Lakuna** [comment]
@Tfarcenim This pull request will update the mod to work in Minecraft versions 1.16.3 and 1.16.4. It's just one line to add license information, which Forge now requires for recent versions.

**Comment by Lakuna** [comment]
@pupnewfster

**Comment by pupnewfster** [comment]
Not sure why I am being pinged here as I cannot merge PRs or anything... I am just someone who has submitted a PR in the past.

**Comment by Lakuna** [comment]
Sorry. I read the contribution wrong, and it seems like the author is inactive.

**Pull request closed without merging**
